openapi: 3.0.0
info:
  title: API de Carritos
  version: 1.0.0
paths:
  /carts:
    get:
      summary: Obtener todos los carritos
      responses:
        "200":
          description: Lista de carritos
        "500":
          description: Error en el servidor
  /carts/{id}:
    get:
      summary: Obtener carrito por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detalles del carrito
        "404":
          description: Carrito no encontrado
        "500":
          description: Error en el servidor
